// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"sync"
	"tracking-order-service/internal/app/domain"
)

// Ensure, that KgxV2RepositoryMock does implement KgxV2Repository.
// If this is not the case, regenerate this file with moq.
var _ KgxV2Repository = &KgxV2RepositoryMock{}

// KgxV2RepositoryMock is a mock implementation of KgxV2Repository.
//
// 	func TestSomethingThatUsesKgxV2Repository(t *testing.T) {
//
// 		// make and configure a mocked KgxV2Repository
// 		mockedKgxV2Repository := &KgxV2RepositoryMock{
// 			GetLastStatusOrderFunc: func(orderStatus string, kgxV2Api domain.KgxV2ResponseBodyApi) domain.ResultKgxV2Status {
// 				panic("mock out the GetLastStatusOrder method")
// 			},
// 			TrackingFunc: func(ctx context.Context, config domain.RepositoryParam) domain.ResultKgxV2Repository {
// 				panic("mock out the Tracking method")
// 			},
// 		}
//
// 		// use mockedKgxV2Repository in code that requires KgxV2Repository
// 		// and then make assertions.
//
// 	}
type KgxV2RepositoryMock struct {
	// GetLastStatusOrderFunc mocks the GetLastStatusOrder method.
	GetLastStatusOrderFunc func(orderStatus string, kgxV2Api domain.KgxV2ResponseBodyApi) domain.ResultKgxV2StatusOrder

	// TrackingFunc mocks the Tracking method.
	TrackingFunc func(ctx context.Context, config domain.RepositoryParam) domain.ResultKgxV2Repository

	// calls tracks calls to the methods.
	calls struct {
		// GetLastStatusOrder holds details about calls to the GetLastStatusOrder method.
		GetLastStatusOrder []struct {
			// OrderStatus is the orderStatus argument value.
			OrderStatus string
			// KgxV2Api is the kgxV2Api argument value.
			KgxV2Api domain.KgxV2ResponseBodyApi
		}
		// Tracking holds details about calls to the Tracking method.
		Tracking []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Config is the config argument value.
			Config domain.RepositoryParam
		}
	}
	lockGetLastStatusOrder sync.RWMutex
	lockTracking           sync.RWMutex
}

// GetLastStatusOrder calls GetLastStatusOrderFunc.
func (mock *KgxV2RepositoryMock) GetLastStatusOrder(orderStatus string, kgxV2Api domain.KgxV2ResponseBodyApi) domain.ResultKgxV2StatusOrder {
	if mock.GetLastStatusOrderFunc == nil {
		panic("KgxV2RepositoryMock.GetLastStatusOrderFunc: method is nil but KgxV2Repository.GetLastStatusOrder was just called")
	}
	callInfo := struct {
		OrderStatus string
		KgxV2Api    domain.KgxV2ResponseBodyApi
	}{
		OrderStatus: orderStatus,
		KgxV2Api:    kgxV2Api,
	}
	mock.lockGetLastStatusOrder.Lock()
	mock.calls.GetLastStatusOrder = append(mock.calls.GetLastStatusOrder, callInfo)
	mock.lockGetLastStatusOrder.Unlock()
	return mock.GetLastStatusOrderFunc(orderStatus, kgxV2Api)
}

// GetLastStatusOrderCalls gets all the calls that were made to GetLastStatusOrder.
// Check the length with:
//     len(mockedKgxV2Repository.GetLastStatusOrderCalls())
func (mock *KgxV2RepositoryMock) GetLastStatusOrderCalls() []struct {
	OrderStatus string
	KgxV2Api    domain.KgxV2ResponseBodyApi
} {
	var calls []struct {
		OrderStatus string
		KgxV2Api    domain.KgxV2ResponseBodyApi
	}
	mock.lockGetLastStatusOrder.RLock()
	calls = mock.calls.GetLastStatusOrder
	mock.lockGetLastStatusOrder.RUnlock()
	return calls
}

// Tracking calls TrackingFunc.
func (mock *KgxV2RepositoryMock) Tracking(ctx context.Context, config domain.RepositoryParam) domain.ResultKgxV2Repository {
	if mock.TrackingFunc == nil {
		panic("KgxV2RepositoryMock.TrackingFunc: method is nil but KgxV2Repository.Tracking was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Config domain.RepositoryParam
	}{
		Ctx:    ctx,
		Config: config,
	}
	mock.lockTracking.Lock()
	mock.calls.Tracking = append(mock.calls.Tracking, callInfo)
	mock.lockTracking.Unlock()
	return mock.TrackingFunc(ctx, config)
}

// TrackingCalls gets all the calls that were made to Tracking.
// Check the length with:
//     len(mockedKgxV2Repository.TrackingCalls())
func (mock *KgxV2RepositoryMock) TrackingCalls() []struct {
	Ctx    context.Context
	Config domain.RepositoryParam
} {
	var calls []struct {
		Ctx    context.Context
		Config domain.RepositoryParam
	}
	mock.lockTracking.RLock()
	calls = mock.calls.Tracking
	mock.lockTracking.RUnlock()
	return calls
}
