// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package service

import (
	"context"
	"sync"
	"tracking-order-service/internal/app/domain"
)

// Ensure, that JntRepositoryMock does implement JntRepository.
// If this is not the case, regenerate this file with moq.
var _ JntRepository = &JntRepositoryMock{}

// JntRepositoryMock is a mock implementation of JntRepository.
//
// 	func TestSomethingThatUsesJntRepository(t *testing.T) {
//
// 		// make and configure a mocked JntRepository
// 		mockedJntRepository := &JntRepositoryMock{
// 			GetLastStatusOrderFunc: func(orderStatus string, jntApi domain.JntResponseBodyApi) domain.ResultJntStatus {
// 				panic("mock out the GetLastStatusOrder method")
// 			},
// 			TrackingFunc: func(ctx context.Context, config domain.RepositoryParam) domain.ResultJntRepository {
// 				panic("mock out the Tracking method")
// 			},
// 		}
//
// 		// use mockedJntRepository in code that requires JntRepository
// 		// and then make assertions.
//
// 	}
type JntRepositoryMock struct {
	// GetLastStatusOrderFunc mocks the GetLastStatusOrder method.
	GetLastStatusOrderFunc func(orderStatus string, jntApi domain.JntResponseBodyApi) domain.ResultJntStatusOrder

	// TrackingFunc mocks the Tracking method.
	TrackingFunc func(ctx context.Context, config domain.RepositoryParam) domain.ResultJntRepository

	// calls tracks calls to the methods.
	calls struct {
		// GetLastStatusOrder holds details about calls to the GetLastStatusOrder method.
		GetLastStatusOrder []struct {
			// OrderStatus is the orderStatus argument value.
			OrderStatus string
			// JntApi is the jntApi argument value.
			JntApi domain.JntResponseBodyApi
		}
		// Tracking holds details about calls to the Tracking method.
		Tracking []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Config is the config argument value.
			Config domain.RepositoryParam
		}
	}
	lockGetLastStatusOrder sync.RWMutex
	lockTracking           sync.RWMutex
}

// GetLastStatusOrder calls GetLastStatusOrderFunc.
func (mock *JntRepositoryMock) GetLastStatusOrder(orderStatus string, jntApi domain.JntResponseBodyApi) domain.ResultJntStatusOrder {
	if mock.GetLastStatusOrderFunc == nil {
		panic("JntRepositoryMock.GetLastStatusOrderFunc: method is nil but JntRepository.GetLastStatusOrder was just called")
	}
	callInfo := struct {
		OrderStatus string
		JntApi      domain.JntResponseBodyApi
	}{
		OrderStatus: orderStatus,
		JntApi:      jntApi,
	}
	mock.lockGetLastStatusOrder.Lock()
	mock.calls.GetLastStatusOrder = append(mock.calls.GetLastStatusOrder, callInfo)
	mock.lockGetLastStatusOrder.Unlock()
	return mock.GetLastStatusOrderFunc(orderStatus, jntApi)
}

// GetLastStatusOrderCalls gets all the calls that were made to GetLastStatusOrder.
// Check the length with:
//     len(mockedJntRepository.GetLastStatusOrderCalls())
func (mock *JntRepositoryMock) GetLastStatusOrderCalls() []struct {
	OrderStatus string
	JntApi      domain.JntResponseBodyApi
} {
	var calls []struct {
		OrderStatus string
		JntApi      domain.JntResponseBodyApi
	}
	mock.lockGetLastStatusOrder.RLock()
	calls = mock.calls.GetLastStatusOrder
	mock.lockGetLastStatusOrder.RUnlock()
	return calls
}

// Tracking calls TrackingFunc.
func (mock *JntRepositoryMock) Tracking(ctx context.Context, config domain.RepositoryParam) domain.ResultJntRepository {
	if mock.TrackingFunc == nil {
		panic("JntRepositoryMock.TrackingFunc: method is nil but JntRepository.Tracking was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Config domain.RepositoryParam
	}{
		Ctx:    ctx,
		Config: config,
	}
	mock.lockTracking.Lock()
	mock.calls.Tracking = append(mock.calls.Tracking, callInfo)
	mock.lockTracking.Unlock()
	return mock.TrackingFunc(ctx, config)
}

// TrackingCalls gets all the calls that were made to Tracking.
// Check the length with:
//     len(mockedJntRepository.TrackingCalls())
func (mock *JntRepositoryMock) TrackingCalls() []struct {
	Ctx    context.Context
	Config domain.RepositoryParam
} {
	var calls []struct {
		Ctx    context.Context
		Config domain.RepositoryParam
	}
	mock.lockTracking.RLock()
	calls = mock.calls.Tracking
	mock.lockTracking.RUnlock()
	return calls
}
